import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" data-oid=".9czjhh">
      <body data-oid="fvl_9n5" className="antialiased w-full">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
