import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppSidebar } from "@/components/app-sidebar";
import { BreadcrumbClientWrapper } from "@/components/breadcrumb-client-wrapper";
import {
  SidebarProvider,
  SidebarInset,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { Separator } from "@radix-ui/react-separator";
import { cookies } from "next/headers";
import { NavActions } from "@/components/nav-actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <SidebarProvider defaultOpen={defaultOpen} data-oid="d5_5sr1">
      <AppSidebar data-oid="i7m9xzx" />
      <SidebarInset data-oid="cr08lkr">
        <header
          className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12"
          data-oid="z81v.5a"
        >
          <div className="flex items-center gap-2 px-4" data-oid=".gr-69y">
            <SidebarTrigger className="-ml-1" data-oid="1jc2eu6" />
            <Separator
              orientation="vertical"
              className="mr-2 data-[orientation=vertical]:h-4"
              data-oid=":qejjun"
            />

            <BreadcrumbClientWrapper data-oid="smo_6mp" />
          </div>
          <div className="ml-auto px-3" data-oid="gjyewqk">
            <NavActions data-oid="5hypg4t" />
          </div>
        </header>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
